### 1. Write functions, along with proper code documentation and formatting;
**A.To check whether a number is prime or not**

In [12]:
def find_prime(n): # defination of function
    c=0
    for i in range(1,n+1):     
        if(n%i == 0):           # checking the number is divisible by how many numbers
            c=c+1
    if(c==2):         # if number is divisible by only 2 numbers return prime
        return "Prime"
    else:           # if number is divisible by more than 2 numbers return Not a prime
        return "Not a Prime" 

n = int(input())     # user input
print("Given number is :",find_prime(n))    # calling the function and printing the output return

17
Given number is : Prime


**B. To find the longest word in a sentence given as input by the user**

In [35]:
def long_word(s):
    s1 = s.split(' ')   # spliting the words by space in to a list
    s2=''
    max_n=0
    for i in range(0,len(s1)):     # iterating through each item in list
        n = len(s1[i])         # checking the length 
        if(n>max_n):
            max_n = n
            s2=s1[i]     
    return s2     # returning the longest word
    
s = input()  # user input
print("The Longest word in a sentence is :",long_word(s))   # calling the function and printing the output return


The train leaves every morning at 18 AM
The Longest word in a sentence is : morning


**C. To find how many times a given user-inputted substring is repeated in another user inputted string**

In [46]:
def find_occurrance(s1,s2):
    res = 0
    n = len(s2)      # length of substring
    for i in range(len(s1)):      # iterating through eact character in a s1
        # checking the s2 in s1 by increasing i by the length of s2
        if s1[i:i+n] == s2:    
            res += 1      
    return res    # return no of occurrances
 
s1 = input()   # string user input
s2 = input()   # substring user input
print("Frequency of substring in given string is :",find_occurrance(s1,s2)) # calling the function and printing the output return


dogcatliondogtigerdog
dog
Frequency of substring in given string is : 3


### 2. Create the following class with the given attributes and methods;

In [89]:
# A. Standard class
class standard:
    # defining constructor and assign the values
    def __init__(self,std_name,no_of_enrolled_students,OGPA):
        self.std_name = std_name
        self.no_of_enrolled_students = no_of_enrolled_students
        self.OGPA = OGPA
    
    # getStd Method
    def getStd(self):
        return self.std_name
    # getEnrolled  Method
    def getEnrolled(self):
        return self.no_of_enrolled_students
    # getOGPA Method
    def getOGPA(self):
        return self.OGPA
    
# B. Students class
class Students(standard):
     # defining constructor and assign the values
    def __init__(self,Name,Roll_No,Standard_name,Math_marks,English_Marks,Science_Marks,Social_Marks):
        self.Name = Name
        self.Roll_No = Roll_No
        self.Standard_name = Standard_name
        self.Math_marks = Math_marks
        self.English_Marks = English_Marks
        self.Science_Marks = Science_Marks
        self.Social_Marks = Social_Marks
    # getName Method
    def getName(self):
        return self.Name
    # getRollNo Method
    def getRollNo(self):
        return self.Roll_No
    # getStd Method
    def getStd(self):
        return self.Standard_name
    # getGPA Method
    def getGPA(self):
        avg_marks = (self.Math_marks+self.English_Marks+self.Science_Marks+self.Social_Marks)/4
        gpa = avg_marks / 9.5      # calculating GPA value
        return round(gpa,2)

# C. creating the objects of each class
# standard class objects
std1 = standard('9th standard',40,9.0)
std2 = standard('7th standard',45,8.9)

# Students class objects
student1 = Students('Uday','23','9th standard',88,92,77,75)
student2 = Students('Ajun','44','7th standard',84,90,74,70)

# Printing the details of student using getters method
print("Name : ",student1.getName())       
print("Roll No : ",student1.getRollNo())
print("Standard : ",student1.getStd())
print("GPA : ",student1.getGPA())


Name :  Uday
Roll No :  23
Standard :  9th standard
GPA :  8.74


**3(a). Create a function to find the indices of a parameter passed to the function in a user inputted array. Ex: f(0,[1,2,0,0,4]) gives [2,3] as output**

In [94]:
def find_indices(n,lst):
    l=[]    # intializing empty list for output storing
    for i in range(len(lst)):       # itterating through the list
        if(lst[i] == n):   
            l.append(i)         # appending the indices
    return l  
    
n = 5   # integer input
lst = [1,4,5,6,5,7]   # list input
print(find_indices(n,lst))

[2, 4]


**3(b). Create a random vector of size 30 and find the mean value**

In [102]:
# import numpy library
import numpy as np
x = np.random.random(30)  # Random 30 items variable
m = x.mean()  # finding mean
print("Mean :",m)  # print mean

Mean : 0.5416042157827737


**3(c). Create a 2d array with 1 on its edges and 0 in all other indices**

In [107]:
# import numpy library
import numpy as np
a = np.ones((4,4))   # made a array with 1 in all values
a[1:-1,1:-1] = 0     # replacing 1 with o except in edges
print(a)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


**3(d). Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.**

In [112]:
# import numpy library
import numpy as np

# made a array with 1 in all values
x = np.zeros((8,8),dtype=int)

# fill with 1 in the alternate rows and columns
x[1::2,::2] = 1
x[::2, 1::2] = 1

print("Checkerboard pattern:")
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
